<?php

use Illuminate\Database\Seeder;

class peminjamanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'1',
        	'kode_apd'=>'A00023',
            'nik'=>'T354767',
            'username'=>'admin1',
            'jumlah_apd'=>'2',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-11',
            'status'=>'Pesan',
            'jenis'=>'1',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'2',
        	'kode_apd'=>'A00014',
            'nik'=>'T354762',
            'username'=>'admin1',
            'jumlah_apd'=>'1',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-11',
            'status'=>'Pesan',
            'jenis'=>'0',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'3',
        	'kode_apd'=>'A00001',
            'nik'=>'T354762',
            'username'=>'admin1',
            'jumlah_apd'=>'1',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-11',
            'status'=>'Pesan',
            'jenis'=>'0',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'4',
        	'kode_apd'=>'A00021',
            'nik'=>'T354764',
            'username'=>'admin1',
            'jumlah_apd'=>'15',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-11',
            'status'=>'Pinjam',
            'jenis'=>'1',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'5',
        	'kode_apd'=>'A00025',
            'nik'=>'T354764',
            'username'=>'admin1',
            'jumlah_apd'=>'15',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-11',
            'status'=>'Pinjam',
            'jenis'=>'1',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'6',
        	'kode_apd'=>'A00016',
            'nik'=>'T354761',
            'username'=>'admin1',
            'jumlah_apd'=>'1',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-15',
            'status'=>'Selesai',
            'jenis'=>'0',
        ));
        DB::table('peminjaman')->insert(array(
            'kode_pinjam'=>'7',
        	'kode_apd'=>'A00003',
            'nik'=>'T354761',
            'username'=>'admin1',
            'jumlah_apd'=>'1',
            'tgl_pinjam'=>'2019-01-11',
            'tgl_kembali'=>'2019-07-15',
            'status'=>'Selesai',
            'jenis'=>'0',
        ));
    }
}
